# Generated by Django 5.0.7 on 2024-08-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_delete_inputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('current_date', models.DateField()),
                ('product_type', models.CharField(max_length=50)),
                ('product_details', models.TextField()),
                ('key_words', models.CharField(max_length=255)),
                ('most_views', models.BooleanField(default=False)),
                ('newest', models.BooleanField(default=False)),
                ('top_rated', models.BooleanField(default=False)),
            ],
        ),
    ]
