# Generated by Django 5.0.7 on 2024-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_clientrequest_key_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='key_words',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='key_words',
            field=models.ManyToManyField(blank=True, to='website.keyword'),
        ),
    ]
