# Generated by Django 5.0.4 on 2024-09-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='client_id',
            new_name='request_id',
        ),
    ]
