# Generated by Django 5.0.4 on 2024-09-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_client_rename_seller_sellerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='product_id',
            field=models.CharField(default=('Product ID', '0'), editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
