# Generated by Django 5.0.4 on 2024-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_sellerproduct_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
