# Generated by Django 5.0.4 on 2024-09-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='client',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='seller',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
