# Generated by Django 5.0.4 on 2024-09-23 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_clientrequest_client_sellerproduct_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='current_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
