# Generated by Django 5.0.4 on 2024-09-23 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_current_date_clientrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
