# Generated by Django 5.0.4 on 2024-09-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_clientrequest_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='start_date',
        ),
    ]
