# Generated by Django 5.0.4 on 2024-10-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_clientrequest_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='end_date',
            field=models.CharField(max_length=11),
        ),
    ]
