# Generated by Django 5.0.4 on 2024-10-07 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_clientrequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='key_words',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
