# Generated by Django 5.0.4 on 2024-10-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_sellerproduct_key_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='most_views',
            new_name='firsthand',
        ),
        migrations.RenameField(
            model_name='clientrequest',
            old_name='newest',
            new_name='secondhand',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='top_rated',
        ),
    ]
