# Generated by Django 5.0.4 on 2024-10-12 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_clientrequest_firsthand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.client'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.seller'),
        ),
    ]
