# Generated by Django 5.0.7 on 2024-08-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='client_id',
            field=models.CharField(default=('Client', 0), editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
