# Generated by Django 5.0.7 on 2024-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_keyword_remove_clientrequest_key_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='key_words',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='key_words',
            field=models.TextField(default=('Client', 0)),
            preserve_default=False,
        ),
    ]
